language: java

stages:
  - Test
  - Release

jobs:
  include:
    - stage : Test
      script:
        - mvn test

    - stage: Release
      if: type != pull_request AND(branch = master OR branch = develop OR branch = seal-config-comply)
      language: java
      before_script:
      - 'if [ "${TRAVIS_BRANCH}" = "develop" ]; then
        export CONTAINER_TAG=develop;
        elif [ "${TRAVIS_BRANCH}" = "seal-config-comply" ]; then
        export CONTAINER_TAG=test-ci;'
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t cbuendiaatos/idp-edugain:${CONTAINER_TAG} .
        - docker push cbuendiaatos/idp-edugain:${CONTAINER_TAG}
