language: java

stages:
  - Test
  - Release

jobs:
  include:
    - stage : Test
      script:
        - mvn test

    - stage: Release
      if: type != pull_request AND(branch = master OR branch = development OR branch = "SM-update-fix")
      language: java
      before_script:
      - 'if [ "${TRAVIS_BRANCH}" = "development" ]; then
            export CONTAINER_TAG="0.0.2";
        elif [ "${TRAVIS_BRANCH}" = "master" ]; then
            export CONTAINER_TAG=latest;
        elif [ $TRAVIS_BRANCH == "SM-update-fix" ]; then
            export CONTAINER_TAG=test1;
	fi'
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t mvjatos/seal-edugain-idp:${CONTAINER_TAG} .
        - docker push mvjatos/seal-edugain-idp:${CONTAINER_TAG}
