language: java

stages:
  - Test
  - Release

jobs:
  include:
    - stage : Test
      script:
        - mvn test

    - stage: Release
      if: type != pull_request AND(branch = mater OR branch = develop)
      language: java
      before_script:
      - 'if [ "${TRAVIS_BRANCH}" = "develop" ]; then
        export CONTAINER_TAG=develop;
        elif [ "${TRAVIS_BRANCH}" = "seal-config-comply" ]; then
        export CONTAINER_TAG=master;'
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t mvjatos/seal-test:${CONTAINER_TAG} .
        - docker push mvjatos/seal-test:${CONTAINER_TAG}
